import "@./globals.css"; // Замыг нь ингэж сольж үзээрэй
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// _components доторх index.ts-ээс зөв импортлогдож байгааг шалгаарай
import { ChatComponent, Navigation } from "./_components"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Image Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="mn"> {/* Монгол хэл дээр бол mn болгож болно */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navigation />
        {/* Хүүхэд элементүүд болон ChatComponent-ийг зөв дарааллаар байрлуулах */}
        <main>
          {children}
        </main>
        <ChatComponent />
      </body>
    </html>
  );
}